### ISSUE TITLE
[Feat] Page des règles du jeu

### ISSUE THREAD

**Issue by JoshuaArus** [JoshuaArus/the_crew_companion#18]
Intégrer les règles du jeu à la page en construction

**Comment by schnapse** [comment]
http://iello.fr/regles/The-Crew_Rulebook.pdf

**Comment by JoshuaArus** [comment]
Bordel 22 pages... t'as du courage 🤣

**Comment by schnapse** [comment]
Ouai mais c'est écrit grand ! Mdr
Je crois je vais faire une petite partie pour qu'on valide la mise en page et le full content après.
